In [43]:
import numpy as np
import pandas as pd


In [44]:
x = ["This was awesome an awesome movie",
     "Great movie! I liked it a lot",
     "Happy Ending! awesome acting by the hero",
     "loved it! truly great",
     "bad not upto the mark",
     "could have been better",
     "Surely a Disappointing movie"]

y = [1,1,1,1,0,0,0] # 1 - Positive, 0 - Negative Class

In [45]:
x_test = ["I was happy & happy and I loved the acting in the movie",
          "The movie I saw was bad"]

# Cleaning the data

In [46]:
import clean_text as ct

In [47]:
x_clean=[ct.getCleanReview(i) for i in x]
xt_clean=[ct.getCleanReview(i) for i in x_test]

In [48]:
print(x_clean)

['awesom awesom movi', 'great movi like lot', 'happi end awesom act hero', 'love truli great', 'bad upto mark', 'could better', 'sure disappoint movi']


# Vectorization

In [49]:
from sklearn.feature_extraction.text import CountVectorizer

In [50]:
cv=CountVectorizer(ngram_range=(1,2))

In [51]:
x_vec=cv.fit_transform(x_clean).toarray()

In [52]:
print(x_vec)
print(x_vec.shape)

[[0 0 2 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 1 1 0 0 0 1 1 0 0 0 0 0 0]
 [1 1 1 1 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1 1 0 0]
 [0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1]
 [0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0]]
(7, 34)


In [53]:
print(cv.get_feature_names())

['act', 'act hero', 'awesom', 'awesom act', 'awesom awesom', 'awesom movi', 'bad', 'bad upto', 'better', 'could', 'could better', 'disappoint', 'disappoint movi', 'end', 'end awesom', 'great', 'great movi', 'happi', 'happi end', 'hero', 'like', 'like lot', 'lot', 'love', 'love truli', 'mark', 'movi', 'movi like', 'sure', 'sure disappoint', 'truli', 'truli great', 'upto', 'upto mark']


In [54]:
##vectorization on the test set

xt_vec=cv.transform(xt_clean).toarray()
print(xt_vec)
cv.get_feature_names()
print(xt_vec.shape)

[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]]
(2, 34)


# Multinomial Naive Bayes

In [55]:
from sklearn.naive_bayes import MultinomialNB,BernoulliNB, GaussianNB

In [56]:
mnb=MultinomialNB()
print(mnb)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)


In [57]:
mnb.fit(x_vec,y)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [58]:
#predictions
mnb.predict(xt_vec)

array([1, 0])

In [59]:
mnb.predict_proba(xt_vec)

array([[0.09580319, 0.90419681],
       [0.61972801, 0.38027199]])

In [67]:
mnb.score(x_vec,y)

1.0

# Multivariate Bernoulli Naive Bayes

In [62]:
bnb=BernoulliNB(binarize=0.0)

In [63]:
print(bnb)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)


In [64]:
bnb.fit(x_vec,y)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [65]:
#predictions
bnb.predict(xt_vec)

array([1, 0])

In [66]:
bnb.predict_proba(xt_vec)

array([[0.10638608, 0.89361392],
       [0.76046221, 0.23953779]])

In [68]:
bnb.score(x_vec,y)

1.0